[versions]
agp = "8.5.0"
kotlin = "2.0.20"
nexus-publish = "2.0.0"
kotlinx-io = "0.5.1"
dokkatoo-html = "2.3.1"

[libraries]
# Plugins
nexus-publish = { module = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin", version.ref = "nexus-publish" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-library = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "agp" }
dokkatoo-html = { module = "dev.adamko.dokkatoo:dokkatoo-plugin", version.ref = "dokkatoo-html" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }